### ISSUE TITLE
Updates to chapter 1

### ISSUE THREAD

**Issue by norcalbiostat** [annakfell/ascnv2#9]
- [x] for each section where it shows how to do something e.g. renaming variables, use tabsets for each method
- [x] add the example on collapsing factor levels using forcats in section 1.10.1
- [x] use a callout box every time i'm referencing another text
- [x] Remove all the SPSS code/discussion
- [x] update the chapter reference code under 1.17.3. I think the new way to ref does not include the `@`

**Comment by annakfell** [comment]
The bulk of the 'saving only selected variables' subheader in 1.15 Export and Save was SPSS examples, so the reference to dplyr select() could be turned into either a callout box note or expanded with an example

**Comment by norcalbiostat** [comment]
Both! Use a green "TIP" callout box and put an example in there.

Also, let's change the "check your knowledge " box earlier to a yellow (caution?) Box

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by annakfell** [comment]
The reference format @sec-name from {#sec-name} at the title should work once Ch12 is imported, it linked (but as Ch3) with a blank test file

**Comment by norcalbiostat** [comment]
Other updates

- [x]  text at bottom of section 1.5

> Right away this tells me that R thinks all variables are numeric integers, not categorical variables. Many of these will have to be changed. We’ll get to that in a moment.

needs to be pulled out of the tabset so  it shows for both

- [x] add tip? note? box on how and why to use `::`  right after the first usage at `janitor::clean_names()``

**Comment by norcalbiostat** [comment]
In 1.10

- [x] move help  box to top that ref's forcats vignette & math 130
- [x] don't load the `car` library, use the shortcut `car::recode`
- [x] figure out where in this whole chapter to put a warning box about package conflicts. (perhaps here is fine b/c tghis is the first place where ther is a conflict) but the `recode` function is in dplyr also and works differently
